// Storing movieLists in an array
const movieLists = [
  "Hacksaw Ridge",
  "Into the Wild",
  "The Terminator",
  "Legend",
  "Joker",
  "The Lion King",
  "Toy Story",
  "Scarface",
  "Godfather",
  "Chucky",
  "Grease",
  "Walk the line",
  "Gladiator",
  "Home Alone",
  "Titanic",
  "Frozen",
  "Moana",
  "Up",
  "Rocky",
  "Die Hard",
  "Braveheart",
  "Slumdog Millionaire",
  "Harry Potter",
  "Inception",
  "Shutter Island",
  "Whiplash",
  "Brokeback Mountain",
  "The Great Escape",
  "Amelie",
  "The Dark Knight",
  "Captain America",
  "Taxi Driver",
  "Good Will Hunting",
  "Beauty And The Beast",
  "Like Stars On Earth",
  "Life of Pi",
  "Inside Out",
  "Forrest Gump",
  "The Shining",
  "Warrior",
  "The Breakfast Club",
  "The Santa Claus",
  "Goodfellas",
  "The Pianist",
  "Fury",
  "Joy",
  "Prisoners",
  "A Star is born",
  "Brothers",
  "Apocalypto",
];
